### 테스트 요청

GET http://localhost:8080/foo
Content-Type: application/json
#Cookie:  SESSION=df067b42-dca2-4cec-8700-3a157b27432a
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.32R7PSHT7sSuBkjm2seF0e0Cc9JxpASbmZGquw4Z9mQ

### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "chcjswo@test.com",
    "password": "1234"
}
