spring:
#    h2:
#        console:
#            enabled: true
#            path: /h2-console
#
#    datasource:
#        url: jdbc:h2:mem:chcjswo
#        username: sa
#        password:
#        driver-class-name: or.h2.Driver

    jpa:
        defer-datasource-initialization: true

    sql:
        init-mode: always

    data:
        web:
            pageable:
                max-page-size: 2000
                default-page-size: 20
                one-indexed-parameters: true
mocadev:
    data:
        name: mocadev
        age: 30
